dist: xenial
language: scala

scala:
  - 2.12.11
  - 2.13.2

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

install:
  - pip install --user codecov

script:
  - sbt "; ++$TRAVIS_SCALA_VERSION; project genericExtras; clean; coverage; test; coverageReport; scalafmtCheck; test:scalafmtCheck; scalafmtSbtCheck;"
  - sbt "; ++$TRAVIS_SCALA_VERSION; project genericExtrasJS; test; scalafmtCheck; test:scalafmtCheck;"
  - codecov

  # See http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
